name: Build and Deploy BlazorChatApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./BlazorChatApp/BlazorChatApp.csproj

    - name: Build
      run: dotnet build ./BlazorChatApp/BlazorChatApp.csproj --no-restore

    - name: Test
      run: dotnet test ./BlazorChatApp.Tests/BlazorChatApp.Tests.csproj

    - name: Publish
      run: dotnet publish ./BlazorChatApp/BlazorChatApp.csproj -c Release -o release